In [18]:
import torch 
import dgl

g = dgl.graph(([0, 0, 1, 5], [1, 2, 2, 0]))
# print(g)
g.ndata['x'] = torch.ones(g.num_nodes(),3)
# print(g.ndata['x'])
g.edata['y'] = torch.randn(g.num_edges(),1)
# print(g.edata['y'])
weights = torch.tensor([0.1, 0.2, 0.3, 0.4])
g.edata['w'] = weights
# print(g.edata['w'])
# g.ndata['x'] = torch.ones(g.num_nodes(),dtype=torch.int32)
print(g.ndata)
print(g.edges()[0]['x'])


{'x': tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])}


TypeError: new(): invalid data type 'str'

In [1]:
import dgl
import torch as th

# 创建一个具有3种节点类型和3种边类型的异构图
graph_data = {
   ('drug', 'interacts', 'drug'): (th.tensor([0, 1]), th.tensor([1, 2])),
   ('drug', 'interacts', 'gene'): (th.tensor([0, 1]), th.tensor([2, 3])),
   ('drug', 'treats', 'disease'): (th.tensor([1]), th.tensor([2]))
}
g = dgl.heterograph(graph_data)
print(g.num_nodes())
print(g.nodes('drug'))
print(g.nodes['drug'])
g.nodes['drug'].data['m'] = th.ones(3, 1)
print(g.is_block)

10
tensor([0, 1, 2])
NodeSpace(data={})
False


In [39]:
import torch.nn as nn
import torch
from dgl.utils import expand_as_pair
linear = nn.Linear(5, 2)
q = torch.ones(4, 5)
print(q)
print(linear(q))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.8726, 0.4696],
        [0.8726, 0.4696],
        [0.8726, 0.4696],
        [0.8726, 0.4696]], grad_fn=<AddmmBackward0>)
